'use strict';

// tests for auth
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('auth', '/src/auth.ts', 'handler');
import { APIGatewayProxyEvent } from 'aws-lambda';

describe('Authentication', () => {
  before((done) => {
    done();
  });

  it('Token unauthenticated user', async () => {
    const data: APIGatewayProxyEvent = {
      type: 'TOKEN',
      authorizationToken: 'dW5hdXRoZW50aWNhdGVk',
      methodArn: 'arn:aws:execute-api:eu-central-1:123456789012:example/prod/POST/{proxy+}',
    };
    const response = wrapped.run(data);
    expect(response).to.not.be.empty;
  });
});

